//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    using System.IO;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;txtMonster&quot;: &quot;Monster (*  = random)&quot;,
        ///  &quot;txtKillFMon&quot;: &quot;Monster (* = random)&quot;,
        ///  &quot;txtKillFItem&quot;: &quot;Item name&quot;,
        ///  &quot;txtKillFQ&quot;: &quot;Quantity (* = any)&quot;,
        ///  &quot;txtPacket&quot;: &quot;%xt%zm%.........&quot;,
        ///  &quot;txtPlayer&quot;: &quot;Player name&quot;,
        ///  &quot;txtAuthor&quot;: &quot;Author&quot;,
        ///  &quot;txtDescription&quot;: &quot;Description&quot;,
        ///  &quot;txtJoin&quot;: &quot;battleon-1e99&quot;,
        ///  &quot;txtJoinCell&quot;: &quot;Enter&quot;,
        ///  &quot;txtJoinPad&quot;: &quot;Spawn&quot;,
        ///  &quot;txtCell&quot;: &quot;Cell&quot;,
        ///  &quot;txtPad&quot;: &quot;Pad&quot;,
        ///  &quot;txtItem&quot;: &quot;Item name&quot;,
        ///  &quot;txtSwapBank&quot;: &quot;Bank item name&quot;,
        ///  &quot;txtSwapInv&quot;: &quot;Inventory item name&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string defaulttext {
            get {
                return ResourceManager.GetString("defaulttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GitHub {
            get {
                object obj = ResourceManager.GetObject("GitHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon GrimoireIcon {
            get {
                object obj = ResourceManager.GetObject("GrimoireIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GrimoireIconBig {
            get {
                object obj = ResourceManager.GetObject("GrimoireIconBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GrimoireIconBig1 {
            get {
                object obj = ResourceManager.GetObject("GrimoireIconBig1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MPGHfavicon {
            get {
                object obj = ResourceManager.GetObject("MPGHfavicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MPGHfavicon16 {
            get {
                object obj = ResourceManager.GetObject("MPGHfavicon16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$type&quot;: &quot;System.Collections.Generic.List`1[[Grimoire.Botting.Commands.Misc.Statements.StatementCommand, Grimoire]], mscorlib&quot;,
        ///  &quot;$values&quot;: [
        ///    {
        ///      &quot;$type&quot;: &quot;Grimoire.Botting.Commands.Misc.Statements.CmdCellIs, Grimoire&quot;,
        ///      &quot;Tag&quot;: &quot;Map&quot;,
        ///      &quot;Text&quot;: &quot;Cell is&quot;,
        ///      &quot;Description1&quot;: &quot;Cell&quot;
        ///    },
        ///    {
        ///      &quot;$type&quot;: &quot;Grimoire.Botting.Commands.Misc.Statements.CmdCellIsNot, Grimoire&quot;,
        ///      &quot;Tag&quot;: &quot;Map&quot;,
        ///      &quot;Text&quot;: &quot;Cell is not&quot;,
        ///      &quot;Description1&quot;: &quot;Cell&quot;
        ///    },
        ///    {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string statementcmds {
            get {
                return ResourceManager.GetString("statementcmds", resourceCulture);
            }
        }

        internal static byte[] aqlitegrimoire => File.ReadAllBytes(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "catgirl.swf"));
        internal static byte[] aqlitegrimoiredebug => File.ReadAllBytes("catgirl.swf");
    }
}
